spring:
    datasource:
        url: jdbc:mysql://invdu.top:3306/nlp?characterEncoding=UTF-8
        username: root
        password: dujiachen123
        driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8081